global:
  scrape_interval: 5s

scrape_configs:
  - job_name: serving_local
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: serving_v1
    metrics_path: /metrics
    static_configs:
      - targets: ["serving-v1:8080"]
  - job_name: serving_v2
    metrics_path: /metrics
    static_configs:
      - targets: ["serving-v2:8080"]
  - job_name: router
    metrics_path: /metrics
    static_configs:
      - targets: ["router:8080"]
