version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: fraud_poc
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraud
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  serving-v1:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      APP_MODULE: src.serving.app:app
      MODEL_VERSION: v1
      MODEL_BUNDLE_PATH: /app/artifacts_phase4
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: fraud_poc
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraud
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8083:8080"

  serving-v2:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      APP_MODULE: src.serving.app:app
      MODEL_VERSION: v2
      MODEL_BUNDLE_PATH: /app/artifacts_phase4_v2
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: fraud_poc
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraud
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8084:8080"

  router:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      APP_MODULE: src.router.app:app
      ROUTER_MODE: shadow
      CANARY_PERCENT: 10
      V1_URL: http://serving-v1:8080/score
      V2_URL: http://serving-v2:8080/score
    depends_on:
      - serving-v1
      - serving-v2
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ../monitoring/grafana/dashboards:/etc/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata:
